require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - lib/**/*.{rb,rake}
    - spec/**/*.rb
    - db/**/*.rb
  Exclude:
    - Schemafile
    - Guardfile
    - vendor/**/*
    - bin/**
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - public/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  NewCops: enable

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - test
    - development
    - staging
    - production

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'config/sitemap.rb'
    - 'config/routes/**'
    - 'factories/**/*'
    - 'spec/**/*'
    - 'config/environments/*'
    - 'db/seeds.rb'

Layout/LineLength:
  Max: 128

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Naming/PredicateName:
  Exclude:
    - 'app/graphql/types/**/*'

Rails/DynamicFindBy:
  AllowedReceivers:
    - MaddressClient::Prefecture
    - MaddressClient::City
    - MaddressClient::Town
  AllowedMethods:
    - find_by_graphql_global_id!

Rails/FilePath:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - 'spec/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

Layout/ParameterAlignment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/MultilineBlockChain:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

RSpec/AnyInstance:
  Exclude:
    - 'spec/support/test_helper.rb'

RSpec/MultipleExpectations:
  Max: 4
